### ISSUE TITLE
Roadmap Cote d'Ivoire

### ISSUE THREAD

**Issue by Leocza** [openfisca/openfisca-cote-d-ivoire#26]
ROADMAP

# 1. Identifier les postes budgétaires (impôts/allocations/subventions/services) qui rapportent/coûtent le plus

- Faire une feuille récapitulative (format csv, séparateur = virgule, sans accent) comportant : 
       - [x] le total des recettes fiscales générées par impôt (utile pour le calage)
       - [x] la part des recettes de chaque impôt dans les recettes totales
       - [] un indicateur allant de 0 à 4 pour déterminer si les données disponibles permettent de calculer l'impôt correctement (0 = pas d'info; 4 = toutes les infos dispo)
       - [] les budgets totaux consacrés à chaque allocation
       - [] le nombre d'individus bénéficiant de ces allocations selon les sources différentes de l'enquête
       - [] les budgets consacrés à la santé et à l'éducation (suivant la méthode de désagrégation choisie)
       - [] le nombre d'individus bénéficiant de ces budgets selon les sources différentes de l'enquête
       - [] la source
- [x] Partager les documents sources (dropbox, drive, ou repos git (mieux non ?))

# 1. Explorer la législation et remplir le wiki []

## Impôts directs []
- [] Impôt général sur le revenu 
- [] Impôt sur les Bénéfices Industriels et Commerciaux 
- [] Contribution National 
- [] Autres ? 

## Impôts indirects []
- [] Taxe sur la valeur ajoutée 
- [] Impôt sur les Bénéfices Industriels et Commerciaux 
- [] Contribution Nationale
- [] Autres ? 

## Allocation et subventions []
- [] subvention 
- [] pension ou rente viagère
- [] allocation social 
- [] allocation chômage 

## Services []
- [] santé
- [] éducation  

# 1. Impôt Général sur le Revenu (ITS)

## 1.1 Revenu imposable 

- []  définir les variables qui entrent dans le calcul du revenu imposable par l'IGR
- []  définir variables/paramètres nécessaires aux abattements
- []  définir les variables/paramètres nécessaires à la prise en compte des cas d'exonérations (si applicable)

## 1.2 Traiter les impôts cédulaires

- [] coder la contribution nationale (avec test [])
- [] l'impôt sur les salaires (avec test [])

## 1.3 Calculer l'IGR

- [] définir le barème 
- [] coder les réductions familiales  (avec test [])
- [] coder la méthode de calcul  (avec test [])

## 1.4 Cotisation payé par l'employeur

- [ ] pour la sécurité sociale ?
- [ ] pour les retraites ?

# 2. Impôts sur les Bénéfices Industriels et Commerciaux (BIC)

## 2.1 revenu imposable 

- []  définir les variables qui entrent dans le calcul du revenu imposable
- []  définir variables/paramètres nécessaires aux abattements
- []  définir les variables/paramètres nécessaires à la prise en compte des cas d'exonérations (si applicable)

## 2.1 calcul 

- [] définir le barème 
- [] coder la méthode de calcul  (avec test [])

# taxe sur la valeur ajoutée (TVA) 

# taxe douanières 

## A l'importation produits pétroliers

# 3. Autres impôts
